---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart epicbook
  service:
    name: epicbook
    state: restarted

- name: Restart EpicBook backend
  systemd:
    name: epicbook
    state: restarted
    enabled: true
